/**
 * 🕵️ KinkScout Bot Integration
 * Specialized bot for KinkScout character generation and management
 */

const TelegramBot = require('node-telegram-bot-api');

class KinkScoutBot {
    constructor(options = {}) {
        this.kinkscoutToken = options.kinkscoutToken || process.env.KINKSCOUT_BOT_TOKEN;
        this.mainBot = options.mainBot;
        this.civitaiIntegration = options.civitaiIntegration;
        this.curatorModule = options.curatorModule;

        if (this.kinkscoutToken) {
            this.bot = new TelegramBot(this.kinkscoutToken, { polling: true });
            this.setupCommands();
            this.log('KinkScout Bot initialized with dedicated token', 'SUCCESS');
        } else {
            this.log('KinkScout Bot token not provided - using main bot', 'INFO');
        }
    }

    setupCommands() {
        if (!this.bot) return;

        // KinkScout character generation
        this.bot.onText(/\/kinkscout(?:@\w+)?\s+(.+)/, async (msg, match) => {
            const chatId = msg.chat.id;
            const scenario = match[1];

            try {
                if (!this.civitaiIntegration) {
                    return this.bot.sendMessage(chatId, '❌ *AI Generation Not Available*\n\nCivitai integration not configured.', { parse_mode: 'Markdown' });
                }

                const isAvailable = await this.civitaiIntegration.checkAutomatic1111Availability();
                if (!isAvailable) {
                    return this.bot.sendMessage(chatId, '❌ *AI Generation Unavailable*\n\nAutomatic1111 WebUI is not running.', { parse_mode: 'Markdown' });
                }

                this.bot.sendMessage(chatId, `🕵️ *Generating KinkScout Character...*\n\nScenario: "${scenario}"\n\n⏳ Creating mystical scout leader...`, { parse_mode: 'Markdown' });

                const result = await this.civitaiIntegration.generateKinkScout(scenario);
                const saved = await this.civitaiIntegration.saveGeneratedImage(result.images[0], `KinkScout: ${scenario}`);

                // Add to curator queue if available
                if (this.curatorModule) {
                    const styledTags = this.civitaiIntegration.generateStylizedTags(`kinkscout ${scenario}`);
                    const contentData = {
                        filename: saved.filename,
                        title: `KinkScout: ${scenario}`,
                        duration: 0,
                        fileSize: saved.fileSize,
                        filePath: saved.filepath,
                        originalUrl: 'ai-kinkscout',
                        regularTags: styledTags.map(tag => tag.replace('#', '')),
                        styledTags: styledTags,
                        description: `AI-generated KinkScout character: ${scenario}`,
                        submittedBy: msg.from,
                        submittedAt: new Date(),
                        source: 'civitai-kinkscout'
                    };

                    this.curatorModule.addToQueue(contentData);
                }

                const tagsText = this.civitaiIntegration.generateStylizedTags(`kinkscout ${scenario}`).join(' ');
                this.bot.sendMessage(chatId, `🕵️ *KinkScout Generated!*\n\n🎯 *Tags:* ${tagsText}\n🎭 *Status:* Added to curator queue\n\n_Your mystical scout leader awaits deployment..._`, { parse_mode: 'Markdown' });

                // Also notify main bot if different
                if (this.mainBot && this.bot !== this.mainBot) {
                    this.mainBot.sendMessage(chatId, `🕵️ *KinkScout character generated by dedicated bot*\n\nScenario: "${scenario}"\n🎯 Tags: ${tagsText}`, { parse_mode: 'Markdown' });
                }

            } catch (error) {
                this.handleError(error, 'KinkScout Generation', chatId);
            }
        });

        // KinkScout mission briefing
        this.bot.onText(/\/mission(?:@\w+)?\s+(.+)/, async (msg, match) => {
            const chatId = msg.chat.id;
            const mission = match[1];

            const briefing = this.generateMissionBriefing(mission);
            this.bot.sendMessage(chatId, briefing, { parse_mode: 'Markdown' });
        });

        // KinkScout status and info
        this.bot.onText(/\/scout(?:@\w+)?/, async (msg) => {
            const chatId = msg.chat.id;

            const statusMessage = `🕵️ *KinkScout Operations Center*\n\n` +
                `🎭 *Available Commands:*\n` +
                `• \`/kinkscout [scenario]\` - Generate scout character\n` +
                `• \`/mission [briefing]\` - Create mission briefing\n` +
                `• \`/scout\` - Show this status\n\n` +
                `🌀 *Current Status:* Operational\n` +
                `🔐 *Security Level:* Underground Elite\n` +
                `🎯 *Mission:* Mystical Content Curation\n\n` +
                `_Your underground scout network awaits orders..._`;

            this.bot.sendMessage(chatId, statusMessage, { parse_mode: 'Markdown' });
        });

        this.bot.on('error', (error) => {
            this.log(`KinkScout Bot error: ${error.message}`, 'ERROR');
        });
    }

    generateMissionBriefing(mission) {
        const briefings = [
            `🕵️ *CLASSIFIED MISSION BRIEFING*\n\n🎯 **Objective:** ${mission}\n\n📋 **Intelligence:**\n• Underground operations required\n• Mystical protocols in effect\n• Curator approval needed\n\n🔐 **Security Level:** ELITE\n⏰ **Timeline:** Immediate deployment\n\n_Agent, your mission parameters are set. Proceed with underground aesthetic protocols._`,

            `🌀 *KINKSCOUT OPERATION BRIEF*\n\n🎭 **Mission:** ${mission}\n\n🛡️ **Equipment Loadout:**\n• Leather tactical gear\n• Mystical communication array\n• Underground network access\n\n🎯 **Success Criteria:**\n• Maintain underground aesthetic\n• Apply proper stylized tags\n• Ensure curator workflow compliance\n\n_Scout leader, initiate mission protocols..._`,

            `🔮 *UNDERGROUND DIRECTIVE*\n\n⚡ **Assignment:** ${mission}\n\n🎪 **Operational Theater:**\n• ʜʏᴘɴᴏғᴇᴛɪꜱʜᴇʟɪᴛᴇ network\n• Curator oversight active\n• Mystical enhancement protocols\n\n🕵️ **Field Agent Status:**\n• Clearance: ELITE\n• Gear: Full tactical loadout\n• Support: AI generation capabilities\n\n_Operation greenlit. Execute with underground precision._`
        ];

        return briefings[Math.floor(Math.random() * briefings.length)];
    }

    handleError(error, context, chatId) {
        this.log(`${context} error: ${error.message}`, 'ERROR');
        if (this.bot && chatId) {
            this.bot.sendMessage(chatId, `❌ *KinkScout Mission Failed*\n\nError during ${context.toLowerCase()}. Command center notified.`, { parse_mode: 'Markdown' });
        }
    }

    log(message, type = 'INFO') {
        const timestamp = new Date().toISOString();
        console.log(`[${timestamp}] KINKSCOUT-${type}: ${message}`);
    }

    // Send message from KinkScout bot
    async sendMessage(chatId, message, options = {}) {
        if (this.bot) {
            return await this.bot.sendMessage(chatId, message, options);
        } else if (this.mainBot) {
            // Prefix message to indicate it's from KinkScout
            const prefixed = `🕵️ **[KinkScout]** ${message}`;
            return await this.mainBot.sendMessage(chatId, prefixed, options);
        }
    }

    // Get bot info
    async getBotInfo() {
        if (this.bot) {
            return await this.bot.getMe();
        }
        return null;
    }
}

module.exports = { KinkScoutBot };
