#!/usr/bin/env node

/**
 * 🎭 HypnoTagger Bot Setup Helper
 * Helps you configure your bot after creating it with BotFather
 */

const https = require('https');
const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

console.log('🎭 HypnoTagger Bot Setup Helper\n');

async function askQuestion(question) {
    return new Promise((resolve) => {
        rl.question(question, (answer) => {
            resolve(answer.trim());
        });
    });
}

async function makeRequest(url) {
    return new Promise((resolve, reject) => {
        https.get(url, (res) => {
            let data = '';
            res.on('data', (chunk) => {
                data += chunk;
            });
            res.on('end', () => {
                try {
                    resolve(JSON.parse(data));
                } catch (parseError) {
                    reject(new Error(`Failed to parse JSON: ${parseError.message}`));
                }
            });
        }).on('error', (httpError) => {
            reject(new Error(`HTTP request failed: ${httpError.message}`));
        });
    });
}

async function getChatId(token) {
    try {
        console.log('\n🔍 Fetching recent updates...');
        const url = `https://api.telegram.org/bot${token}/getUpdates`;
        const response = await makeRequest(url);

        if (!response.ok) {
            console.log('❌ Error:', response.description);
            return null;
        }

        if (response.result.length === 0) {
            console.log('⚠️  No messages found. Please:');
            console.log('   1. Send a message to your bot (like /start)');
            console.log('   2. Run this script again');
            return null;
        }

        console.log('\n📋 Available chats:');
        const chats = new Map();

        response.result.forEach((update, index) => {
            if (update.message) {
                const chat = update.message.chat;
                const key = `${chat.type}_${chat.id}`;
                if (!chats.has(key)) {
                    chats.set(key, chat);
                    console.log(`   ${index + 1}. ${chat.type}: ${chat.title || chat.first_name || 'Unknown'} (ID: ${chat.id})`);
                }
            }
        });

        if (chats.size === 1) {
            const chat = Array.from(chats.values())[0];
            console.log(`\n✅ Using chat: ${chat.title || chat.first_name || 'Unknown'} (ID: ${chat.id})`);
            return chat.id;
        }

        const choice = await askQuestion('\nEnter the number of the chat to use: ');
        const chatArray = Array.from(chats.values());
        const selectedChat = chatArray[parseInt(choice) - 1];

        if (selectedChat) {
            return selectedChat.id;
        } else {
            console.log('❌ Invalid choice');
            return null;
        }
    } catch (error) {
        console.log('❌ Error fetching updates:', error.message);
        return null;
    }
}

async function createEnvFile(token, chatId, kinkscoutToken = '') {
    const envContent = `# 🎭 HypnoTagger Bot Configuration
# Generated by setup helper

# Telegram Bot Token from @BotFather
BOT_TOKEN=${token}

# 🕵️ KinkScout Bot Token (optional - for specialized character generation)
KINKSCOUT_BOT_TOKEN=${kinkscoutToken}

# Chat ID where bot will send tagged videos
CHAT_ID=${chatId}

# 🌀 Fetish Hypno Hub Architecture - Multi-Channel Configuration
# Add your channel IDs below for complete curator workflow

# Channel IDs for Fetish Hypno Hub Distribution
VAULT_CHANNEL_ID=          # ʜʏᴘɴᴏғᴇᴛɪꜱʜᴠᴀᴜʟᴛ 🔓 (Public Teasers)
ELITE_CHANNEL_ID=          # ʜʏᴘɴᴏғᴇᴛɪꜱʜᴇʟɪᴛᴇ 🔐 (VIP Full Access)
LOUNGE_CHANNEL_ID=         # ʜʏᴘɴᴏғᴇᴛɪꜱʜʟᴏᴜɴɢᴇ 💬 (Chat/Discussion)
CURATOR_ROOM_ID=           # ᴡᴇɪʀᴅʜʏᴘɴᴏʙᴀᴛɪɴɢᴠᴀᴜʟᴛ 🧠 (Private Curator Room)

# Curator Access Control (Telegram User IDs)
ADMIN_CURATORS=            # Full admin access (comma-separated)
SENIOR_CURATORS=           # Senior curator permissions (comma-separated)
JUNIOR_CURATORS=           # Junior curator permissions (comma-separated)
TRAINEE_CURATORS=          # Trainee/view-only access (comma-separated)

# Optional: Set to 'development' for testing
NODE_ENV=production

# Optional: Log level (error, warn, info, debug)
LOG_LEVEL=info

# Optional: Maximum file size for downloads (in MB)
MAX_FILE_SIZE=50

# Optional: Maximum video duration (in seconds) 
MAX_DURATION_SECONDS=3600

# Optional: Temporary directory for downloads
TEMP_DIR=/tmp
`;

    const fs = require('fs');
    fs.writeFileSync('.env', envContent);
    console.log('\n✅ Created .env file with your configuration!');
}

async function main() {
    try {
        console.log('Follow these steps to create your bot:\n');
        console.log('1. Open Telegram and search for @BotFather');
        console.log('2. Send /newbot to BotFather');
        console.log('3. Choose a name (e.g., "HypnoTagger Bot")');
        console.log('4. Choose a username ending with "bot" (e.g., "hypnotagger_bot")');
        console.log('5. Copy the bot token BotFather gives you\n');

        const token = await askQuestion('Enter your main bot token: ');

        if (!token) {
            console.log('❌ Bot token is required');
            process.exit(1);
        }

        console.log('\n🕵️ Optional: KinkScout Bot Setup');
        console.log('If you have a second bot for KinkScout character generation, enter its token.');
        console.log('Otherwise, just press Enter to skip.\n');

        const kinkscoutToken = await askQuestion('Enter KinkScout bot token (optional): ');

        console.log('\nNow add your bot to a chat/channel and send it a message (like /start)');
        await askQuestion('Press Enter when you\'ve sent a message to your bot...');

        const chatId = await getChatId(token);

        if (chatId) {
            await createEnvFile(token, chatId, kinkscoutToken);

            console.log('\n🚀 Your bot is ready! Next steps:');
            console.log('   1. Follow TELEGRAM-SETUP-GUIDE.md to create channels');
            console.log('   2. Use SETUP-CHECKLIST.md to track progress');
            console.log('   3. Run: node get-channel-ids.js');
            console.log('   4. Launch: ./start-hub.sh');
            console.log('\n💡 Test your bot with: /submit <video_url>');
            if (kinkscoutToken) {
                console.log('🕵️ KinkScout commands: /generate and /kinkscout');
            }
        } else {
            console.log('\n❌ Could not determine chat ID. Please check the steps above.');
        }
    } catch (error) {
        console.log('❌ Setup failed:', error.message);
    } finally {
        rl.close();
    }
}

main();
